/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const build_env: () => any;
export const run: (a: any, b: number, c: number, d: number, e: number) => any;
export const __wbg_state_free: (a: number, b: number) => void;
export const state_get: (a: number, b: number, c: number) => any;
export const state_peers: (a: number) => any;
export const state_message_progress: (a: number) => any;
export const __wbg_transitionfrontier_free: (a: number, b: number) => void;
export const __wbg_transitionfrontierbestchain_free: (a: number, b: number) => void;
export const transitionfrontier_best_chain: (a: number) => number;
export const transitionfrontierbestchain_user_commands: (a: number) => any;
export const __wbg_rpcsender_free: (a: number, b: number) => void;
export const rpcsender_state: (a: number) => number;
export const rpcsender_ledger: (a: number) => number;
export const rpcsender_status: (a: number) => any;
export const rpcsender_make_heartbeat: (a: number) => any;
export const __wbg_ledger_free: (a: number, b: number) => void;
export const __wbg_ledgerselected_free: (a: number, b: number) => void;
export const __wbg_ledgeraccounts_free: (a: number, b: number) => void;
export const ledger_latest: (a: number) => number;
export const ledgerselected_accounts: (a: number) => number;
export const ledgeraccounts_all: (a: number) => any;
export const __wbg_stats_free: (a: number, b: number) => void;
export const stats_actions: (a: number, b: any) => any;
export const stats_sync: (a: number, b: number) => any;
export const stats_block_producer: (a: number) => any;
export const __wbg_transactionpool_free: (a: number, b: number) => void;
export const __wbg_transactionpoolinject_free: (a: number, b: number) => void;
export const transactionpool_inject: (a: number) => number;
export const transactionpool_get: (a: number) => any;
export const transactionpoolinject_payment: (a: number, b: any) => any;
export const rpcsender_transaction_pool: (a: number) => number;
export const rpcsender_transition_frontier: (a: number) => number;
export const rpcsender_stats: (a: number) => number;
export const wasm_thread_entry_point: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure182_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf3ca83353bc1791d: (a: number, b: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hebd9022714556fe5: (a: number, b: number) => void;
export const closure6377_externref_shim: (a: number, b: number, c: any) => void;
export const closure6398_externref_shim: (a: number, b: number, c: any) => void;
export const closure6419_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
